[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "stack_lang_engine"
version = "0.0.3"
description = "An engine for creating stack-oriented DSLs or mini-programming languages."
readme = "README.md"
requires-python = ">=3.8"
license = "GPL-3.0-or-later"

[project.urls]
Repository = "https://github.com/MrHacer201145/SLE/"
